name: "Refresh Packages"
on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types: 
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@main
        with:
          submodules: recursive
      - name: install depend
        run: |
          sudo apt update 2>>/dev/null 1>>/dev/null
          sudo apt install dpkg-dev bzip2 xz-utils zstd -y
      - name: Refresh Packages
        run: |
          rm -rf ./Packages*
          dpkg-scanpackages -m ./debs /dev/null >./Packages
          bzip2 -v -k -9 Packages
          xz -v -k -9 --extreme Packages
          zstd --ultra -22 -k Packages -o Packages.zst
      - name: save change if local change
        run: |
          git config --global user.email 'action@github.com'
          git config --global user.name 'GitHub Action'
          git add .
          if ! git diff --staged --exit-code 1>>/dev/null; then
            git commit -m 'Refresh Packages'
            git push
          fi
      - uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 0
